services:
  db-grachev:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docker_grachev_1
    ports:
      - "5432:5432"
    volumes:
      - pgdata-grachev:/var/lib/postgresql/data

  app-grachev:
    build: .
    restart: unless-stopped
    ports:
      - "${PORT_EXPOSE}:${PORT}"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db-grachev:5432/docker_grachev_1?schema=public
    depends_on:
      - db-grachev

volumes:
  pgdata-grachev:
