services:
  db-grachev:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docker_grachev_1
    ports:
      - "5432:5432"
    volumes:
      - pgdata-grachev:/var/lib/postgresql/data

  minio-grachev:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-grachev:/data

  app-grachev:
    build: .
    restart: unless-stopped
    ports:
      - "${PORT_EXPOSE}:${PORT}"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db-grachev:5432/docker_grachev_1?schema=public
      MINIO_HOST: minio-grachev
      MINIO_PORT: "9000"
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: minio-bucket-1
    depends_on:
      - db-grachev
      - minio-grachev

volumes:
  pgdata-grachev:
  minio-grachev:
